/**
 * Sentences for measuring the offline scorer against Jev (Phase 1, Checkpoint 7).
 * No expected labels: Jev's answer is the reference, and every disagreement gets read by a human.
 * Groups only organize the report.
 */
export const SAMPLES: Record<string, string[]> = {
  // The examples the offline rules were written against (mock.test.ts). Expect high agreement.
  existing: [
    "dinner with priya friday 8pm",
    "remind me to call mom tomorrow",
    "buy milk, eggs, bread and coffee",
    "25 min focus",
    "timer 10 minutes",
    "meditate every morning",
    "gym 3x a week",
    "#ff6b35",
    "a warm sunset orange",
    "minecraft diamond",
    "tiffany blue",
    "discord blurple",
    "the color of the ocean",
    "split 2400 between 3",
    "spent 450 on uber",
    "5 miles in km",
    "72f to c",
    "18% of 3450",
    "(120+80)*3",
    "flight to goa next weekend",
    "pizza or burgers for friday?",
    "rahul 98200 12345 rahul@mail.com",
    "https://vercel.com/blog check later",
    "i keep thinking about how quiet the city felt this morning",
    "days until christmas",
    "how many days till my birthday on dec 12",
    "3pm pst in ist",
    "what time is it in tokyo",
    "roll 2d6",
    "flip a coin",
    "random number 1-100",
    "read 12 books this year, 4 done",
    "4 of 10 workouts",
    "bug checkout broken on safari @riya p1 by friday",
    "checkout broken on safari high priority @sara",
    "fix login redirect loop",
    "story: users can export reports as pdf",
    "i have an issue with the login page",
    "update the readme cc @sam",
    "cab to client site 640 billable",
    "lunch with client 1200 reimbursable",
  ],
  // New: work items phrased the way people actually write them.
  issue: [
    "signup button does nothing on android",
    "payments page throws 500 after deploy",
    "add dark mode to the dashboard",
    "as a user i want to reset my password by email",
    "migrate the db to postgres 17 @arjun",
    "search results are slow for big accounts",
    "chekout broken on safari @sharon and fix it by tommorow as its high priority",
    "memory usage high on server",
    "typo on the pricing page",
    "investigate why emails go to spam",
    "users can't upload files over 5mb",
    "refactor auth middleware, low priority",
    "the app crashes when i rotate my phone",
    "add csv export for invoices @neha p2",
    "login fails for sso users since monday",
  ],
  // New: neighbours the issue card must NOT steal.
  boundary: [
    "remind me to fix checkout friday",
    "fix checkout, update readme, deploy",
    "email riya@acme.com about the api",
    "print my train ticket friday",
    "call mom tomorrow",
    "standup with the team at 10am",
    "sync with @riya about the roadmap tomorrow 3pm",
    "my laptop is broken again ugh",
    "buy a new charger",
    "book a table for 4 at 8",
    "pay electricity bill",
    "the fix for burnout is rest, i think",
    "review pr 482 before lunch",
    "deploy friday or monday?",
    "high priority: call the bank",
  ],
  // New: everyday cards with messier phrasing than the test examples.
  everyday: [
    "coffee with ananya sat 11",
    "remind me 2moro to water plants",
    "groceries: rice, dal, onions, curd",
    "10 min break",
    "run every evening",
    "paid 1,299 for headphones",
    "zomato 380",
    "split 1800 dinner with rahul and anna",
    "6 ft in cm",
    "15% tip on 2400",
    "trip to manali in december",
    "thai or italian tonight?",
    "priya +91 98765 43210",
    "github.com/vercel/next.js",
    "how long until new year",
    "what's 9am ist in london",
    "pick a random number between 1 and 6",
    "saved 40000 of 100000 for the trip",
    "feeling grateful for this week",
    "idea: a todo app that guesses the type",
  ],
  // New: typos, fragments and mixed intents.
  messy: [
    "dinr with sam tmrw 8",
    "remnd me to pay rent",
    "lunch with sam friday 1pm and remind me to book a table",
    "split the uber 600 and remind me to collect it",
    "bug",
    "fix",
    "@riya",
    "p1",
    "asap",
    "tomorrow",
  ],
};

/**
 * Two-intent lines (Phase 2, Checkpoint 6), with the outcome we want. Unlike SAMPLES, these carry
 * labels: whether a line is one thing or two is a product decision, not the classifier's call.
 */
export const PAIR_SAMPLES: [text: string, expect: "two" | "one"][] = [
  ["lunch with sam friday 1pm and remind me to book a table", "two"],
  ["split the uber 600 and remind me to collect it", "two"],
  ["coffee with riya at 4; remind me to bring the deck", "two"],
  ["dinner with priya friday 8pm and remind me to pay rent", "two"],
  ["standup monday 10am; bug login broken on safari @riya", "two"],
  ["spent 450 on uber and remind me to file it", "two"],
  ["flight to goa next weekend and also remind me to renew my passport", "two"],
  ["25 min focus and then remind me to stretch", "two"],
  ["bug checkout broken @riya p1; remind me to follow up friday", "two"],
  ["buy milk, eggs and bread and also remind me to pay rent", "two"],
  ["call with the vendor tomorrow 3pm. remind me to send the contract", "two"],
  ["pizza or burgers for friday? and remind me to order", "two"],
  ["meditate every morning; remind me to buy a mat", "two"],
  ["dinner tomorrow 8pm and also split 1200 between 3", "two"],
  ["lunch with sam and riya friday", "one"],
  ["buy milk and eggs and bread", "one"],
  ["split 900 between me and sam", "one"],
  ["chekout broken on safari @sharon and fix it by tommorow", "one"],
  ["idea: a todo app that guesses the type. maybe later", "one"],
  ["remind me to call mom and then go to the gym", "one"],
  ["flight to goa then train to pune", "one"],
  ["remind me to call mom and also remind me to pay rent", "one"],
  ["buy milk; eggs; bread", "one"],
  ["meet dr. rao friday at 5 p.m. with sam", "one"],
];
